"""empty message

Revision ID: 47b4010e2ce0
Revises: ab897d6f7cf6
Create Date: 2018-02-04 16:57:34.038111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b4010e2ce0'
down_revision = 'ab897d6f7cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
